indicator("BullionAI", true);
var emaLen = input.int(50);
var rsiLen = input.int(14);
var atrLen = input.int(14);
var atrMult = input.float(1.5);
var stAtr = input.int(10);
var stFactor = input.float(3);
var emaTrend = Std.ema(_series_close, emaLen, context);
var rsi = Std.rsi(_series_close, rsiLen, context);
var atr = Std.atr(atrLen, context);
var [supertrend, direction] = Std.supertrend(stFactor, stAtr, context);
var [macdLine, macdSignal, _] = StdPlus.macd(context, _series_close, 12, 26, 9);
var trendBull = (direction < 0);
var trendBear = (direction > 0);
var momentumBull = ((rsi > 50) && (macdLine > macdSignal));
var momentumBear = ((rsi < 50) && (macdLine < macdSignal));
var buyCondition = (trendBull && momentumBull);
var sellCondition = (trendBear && momentumBear);
var lastSignal = _pineVar("lastSignal", () => ("NONE"));
var tradeStatus = _pineVar("tradeStatus", () => ("CLOSED"));
var entryPrice = _pineVar("entryPrice", () => (NaN));
var trailSL = _pineVar("trailSL", () => (NaN));
var exitSL = _pineVar("exitSL", () => (NaN));
var points = _pineVar("points", () => (NaN));
var maxHigh = _pineVar("maxHigh", () => (NaN));
var maxLow = _pineVar("maxLow", () => (NaN));
var maxProfit = _pineVar("maxProfit", () => (NaN));
var entryYear = _pineVar("entryYear", () => (NaN));
var entryMonth = _pineVar("entryMonth", () => (NaN));
var entryDay = _pineVar("entryDay", () => (NaN));
var entryHour = _pineVar("entryHour", () => (NaN));
var entryMinute = _pineVar("entryMinute", () => (NaN));
var exitYear = _pineVar("exitYear", () => (NaN));
var exitMonth = _pineVar("exitMonth", () => (NaN));
var exitDay = _pineVar("exitDay", () => (NaN));
var exitHour = _pineVar("exitHour", () => (NaN));
var exitMinute = _pineVar("exitMinute", () => (NaN));
var newBuy = (buyCondition && (tradeStatus === "CLOSED"));
var newSell = (sellCondition && (tradeStatus === "CLOSED"));
if ((newBuy || newSell)) {
  (entryPrice = _pineSetVar("entryPrice", close));
  (entryYear = _pineSetVar("entryYear", year));
  (entryMonth = _pineSetVar("entryMonth", month));
  (entryDay = _pineSetVar("entryDay", dayofmonth));
  (entryHour = _pineSetVar("entryHour", hour));
  (entryMinute = _pineSetVar("entryMinute", minute));
  (trailSL = _pineSetVar("trailSL", NaN));
  (exitSL = _pineSetVar("exitSL", NaN));
  (points = _pineSetVar("points", NaN));
  (maxHigh = _pineSetVar("maxHigh", high));
  (maxLow = _pineSetVar("maxLow", low));
  (maxProfit = _pineSetVar("maxProfit", NaN));
  (exitYear = _pineSetVar("exitYear", NaN));
  (exitMonth = _pineSetVar("exitMonth", NaN));
  (exitDay = _pineSetVar("exitDay", NaN));
  (exitHour = _pineSetVar("exitHour", NaN));
  (exitMinute = _pineSetVar("exitMinute", NaN));
  (tradeStatus = _pineSetVar("tradeStatus", "OPEN"));
  (lastSignal = _pineSetVar("lastSignal", (newBuy ? "BUY" : "SELL")));
}
var atrSL_buy = (close - (atr * atrMult));
var atrSL_sell = (close + (atr * atrMult));
var rawBuySL = Math.max(supertrend, atrSL_buy);
var rawSellSL = Math.min(supertrend, atrSL_sell);
(maxProfit = _pineSetVar("maxProfit", (maxHigh - entryPrice)));
(maxProfit = _pineSetVar("maxProfit", (entryPrice - maxLow)));
var slHitSell = ((lastSignal === "SELL") && (close >= trailSL));
var exitDate = (tradeStatus === "CLOSED");
h = ((h === 0) ? 12 : h);
var ampm = ((entryHour >= 12) ? "PM" : "AM");
var entryTime = ((((String(h) + ":") + String(entryMinute)) + " ") + ampm);
var eh = (exitHour % 12);
eh = ((eh === 0) ? 12 : eh);
var exitAmpm = ((exitHour >= 12) ? "PM" : "AM");
var exitTime = (tradeStatus === "CLOSED");
Std.plotshape(newSell, location.abovebar, shape.labeldown, color.red, "SELL", color.white);
Std.plot(trailSL, ((lastSignal === "BUY") ? color.lime : color.red), 3, plot.style_linebr);
var panel = _pineVar("panel", () => (table.new(position.bottom_right, 2, 11, _colorRgb(15, 15, 18), _colorRgb(120, 120, 120), 2, NaN, 1)));
if (barstate.islast) {
  table.cell(panel, 0, 0, "BULLIONAI PRO", NaN, NaN, color.black, NaN, NaN, NaN, _colorRgb(190, 150, 25));
  table.cell(panel, 1, 0, "", NaN, NaN, color.black, NaN, NaN, NaN, _colorRgb(190, 150, 25));
  table.cell(panel, 0, 1, "Trade", NaN, NaN, color.silver);
  table.cell(panel, 1, 1, lastSignal, NaN, NaN, ((lastSignal === "BUY") ? color.lime : color.red));
  table.cell(panel, 0, 2, "Status", NaN, NaN, color.silver);
  table.cell(panel, 1, 2, tradeStatus, NaN, NaN, ((tradeStatus === "OPEN") ? color.yellow : color.white));
  table.cell(panel, 0, 3, "Entry Price", NaN, NaN, color.silver);
  table.cell(panel, 1, 3, String(Math.round(entryPrice)), NaN, NaN, color.white);
  table.cell(panel, 0, 4, "Trail SL", NaN, NaN, color.silver);
  table.cell(panel, 1, 4, String(Math.round(trailSL)), NaN, NaN, color.orange);
  table.cell(panel, 0, 5, ((lastSignal === "BUY") ? "Highest" : "Lowest"), NaN, NaN, color.silver);
  table.cell(panel, 1, 5, maxPriceText, NaN, NaN, color.aqua);
  table.cell(panel, 0, 6, "Current P/L", NaN, NaN, color.silver);
  table.cell(panel, 1, 6, currentPLText, NaN, NaN, ((tradeStatus === "OPEN") ? ((currentPL >= 0) ? color.lime : color.red) : color.white));
  table.cell(panel, 0, 7, "Best P/L", NaN, NaN, color.silver);
  table.cell(panel, 1, 7, maxProfitText, NaN, NaN, color.lime);
  table.cell(panel, 0, 8, "Realized P/L", NaN, NaN, color.silver);
  table.cell(panel, 1, 8, pointsText, NaN, NaN, ((points >= 0) ? color.lime : color.red));
  table.cell(panel, 0, 9, "Entry", NaN, NaN, color.silver);
  table.cell(panel, 1, 9, ((entryDate + "  ") + entryTime), NaN, NaN, color.white);
  table.cell(panel, 0, 10, "Exit", NaN, NaN, color.silver);
  table.cell(panel, 1, 10, ((tradeStatus === "CLOSED") ? ((exitDate + "  ") + exitTime) : "-"), NaN, NaN, color.white);
}
alertcondition(newBuy, "BUY SIGNAL", "BUY {{ticker}}");
alertcondition(newSell, "SELL SIGNAL", "SELL {{ticker}}");